apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service
spec:
  selector:
    app: {{ include "chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}